# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useruser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='useruser',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='useruser',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='UserUser',
        ),
    ]
