# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20160529_1941'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='gamecharacter',
        #     name='is_pc',
        #     field=models.BooleanField(default=False),
        # ),
    ]
