# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20160602_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameasset',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameasset',
            name='stat_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameasset',
            name='stat_value',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamelocation',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelocation',
            name='stat_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelocation',
            name='stat_value',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamemap',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemap',
            name='stat_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemap',
            name='stat_value',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamenpc',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamenpc',
            name='stat_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamenpc',
            name='stat_value',
            field=models.TextField(default=''),
        ),
        # migrations.AlterField(
        #     model_name='gamecharacter',
        #     name='game',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Game'),
        # ),
        migrations.AlterUniqueTogether(
            name='gameasset',
            unique_together=set([('game', 'stat_type', 'stat_value')]),
        ),
        # migrations.AlterUniqueTogether(
        #     name='gamecharacter',
        #     unique_together=set([('game', 'character', 'stat_type', 'stat_value')]),
        # ),
        migrations.AlterUniqueTogether(
            name='gamelocation',
            unique_together=set([('game', 'stat_type', 'stat_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamemap',
            unique_together=set([('game', 'stat_type', 'stat_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamenpc',
            unique_together=set([('game', 'stat_type', 'stat_value')]),
        ),
    ]
