# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20160602_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameasset',
            old_name='stat_type',
            new_name='stat_name',
        ),
        # migrations.RenameField(
        #     model_name='gamecharacter',
        #     old_name='stat_type',
        #     new_name='stat_name',
        # ),
        migrations.RenameField(
            model_name='gamelocation',
            old_name='stat_type',
            new_name='stat_name',
        ),
        migrations.RenameField(
            model_name='gamemap',
            old_name='stat_type',
            new_name='stat_name',
        ),
        migrations.RenameField(
            model_name='gamenpc',
            old_name='stat_type',
            new_name='stat_name',
        ),
        migrations.AddField(
            model_name='gameasset',
            name='val_type',
            field=models.CharField(choices=[('NUM', 'NUMERIC'), ('TXT', 'TEXT')], default='TXT', max_length=4),
            preserve_default=False,
        ),
        # migrations.AddField(
        #     model_name='gamecharacter',
        #     name='val_type',
        #     field=models.CharField(choices=[('NUM', 'NUMERIC'), ('TXT', 'TEXT')], default='TXT', max_length=4),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='gamelocation',
            name='val_type',
            field=models.CharField(choices=[('NUM', 'NUMERIC'), ('TXT', 'TEXT')], default='TXT', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemap',
            name='val_type',
            field=models.CharField(choices=[('NUM', 'NUMERIC'), ('TXT', 'TEXT')], default='TXT', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamenpc',
            name='val_type',
            field=models.CharField(choices=[('NUM', 'NUMERIC'), ('TXT', 'TEXT')], default='TXT', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gameasset',
            unique_together=set([('game', 'stat_name', 'stat_value')]),
        ),
        # migrations.AlterUniqueTogether(
        #     name='gamecharacter',
        #     unique_together=set([('game', 'character', 'stat_name', 'stat_value')]),
        # ),
        migrations.AlterUniqueTogether(
            name='gamelocation',
            unique_together=set([('game', 'stat_name', 'stat_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamemap',
            unique_together=set([('game', 'stat_name', 'stat_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamenpc',
            unique_together=set([('game', 'stat_name', 'stat_value')]),
        ),
    ]
