# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20160603_0223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameasset',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gameasset',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='gamelocation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gamelocation',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='gamemap',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gamemap',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='gamenpc',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='gamenpc',
            name='game',
        ),
        # migrations.RemoveField(
        #     model_name='gamecharacter',
        #     name='stat_name',
        # ),
        # migrations.RemoveField(
        #     model_name='gamecharacter',
        #     name='stat_value',
        # ),
        # migrations.RemoveField(
        #     model_name='gamecharacter',
        #     name='val_type',
        # ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='GameAsset',
        ),
        migrations.DeleteModel(
            name='GameLocation',
        ),
        migrations.DeleteModel(
            name='GameMap',
        ),
        migrations.DeleteModel(
            name='GameNPC',
        ),
    ]
