# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20160603_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=255)),
                ('stat_value', models.TextField(default='')),
                ('val_type', models.CharField(choices=[('NUM', 'NUMERIC'), ('TXT', 'TEXT'), ('IMG', 'IMAGE')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='GameCharacterCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('NPC', 'NPC'), ('LOC', 'Location')], max_length=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.Game')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=255)),
                ('stat_value', models.TextField(default='')),
                ('val_type', models.CharField(choices=[('NUM', 'NUMERIC'), ('TXT', 'TEXT'), ('IMG', 'IMAGE')], max_length=4)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='campaigns.GameItem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gamecharacter',
            unique_together=set([('game', 'character')]),
        ),
        migrations.AddField(
            model_name='gamecharactercharacter',
            name='from_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='campaigns.GameCharacter'),
        ),
        migrations.AddField(
            model_name='gamecharactercharacter',
            name='to_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonded_to', to='campaigns.GameCharacter'),
        ),
        migrations.AddField(
            model_name='characterstat',
            name='game_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='campaigns.GameCharacter'),
        ),
        migrations.AlterUniqueTogether(
            name='itemstat',
            unique_together=set([('item', 'stat_name', 'stat_value')]),
        ),
        migrations.AlterUniqueTogether(
            name='gameitem',
            unique_together=set([('game', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamecharactercharacter',
            unique_together=set([('from_character', 'to_character', 'bond')]),
        ),
        migrations.AlterUniqueTogether(
            name='characterstat',
            unique_together=set([('game_character', 'stat_name', 'stat_value')]),
        ),
    ]
