# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20160604_2013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useruser',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='useruser',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='useruser',
            name='to_user',
        ),
        migrations.AlterField(
            model_name='usergame',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='last_active_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserUser',
        ),
    ]
