# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20160607_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_active_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
