# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_auto_20160705_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecharactercharacter',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
